# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: making web stuff
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - vendor
hightlighter: pygments
keys:
  #ga: UA-19230806-1
name: www.semper-fit.net
permalink: pretty
source: .
timezone: America/New_York
url: http://www.semper-fit.net
gems:
  - jekyll-sitemap
