# GitHub presets
safe: true
lsi: false

# custom settings
author: David Fulps
author_email: david@semper-fit.net
author_phone: (609) 790 2447
description: The Trainer You've Been Looking For
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - vendor
keys:
  ga: UA-19251223-1
name: www.semper-fit.net
permalink: pretty
source: .
timezone: America/New_York
url: http://www.semper-fit.net
gems:
  - jekyll-sitemap
